# apps/graph_ai/pipeline_bridge.py
# -*- coding: utf-8 -*-

from __future__ import annotations

from typing import Any, Dict, Optional

from apps.graph_ai.generator import generate_graph_from_prompt
from agent.pipeline import run_pipeline


# ---------------------------------------------------------
# Graph -> GraphEval task conversion
# ---------------------------------------------------------

def graph_to_task(graph_data: Dict[str, Any], *, task_id: str = "graph_ai_task") -> Dict[str, Any]:
    """
    Convert a simple graph generated by Graph AI into a GraphEval task format.

    Expected graph_data format:
    {
        "name": "WebApp",
        "nodes": {"UI": 1, "Service": 2, "DB": 3},
        "edges": [["UI", "Service"], ["Service", "DB"]]
    }

    Output task_def format:
    {
        "id": ...,
        "title": ...,
        "nodes": [{"id": "...", "layer": 1}, ...],
        "constraints": {...},
        "goal": {...}
    }
    """
    nodes = []
    node_map = graph_data.get("nodes") or {}

    for nid, layer in node_map.items():
        nodes.append({
            "id": str(nid),
            "layer": int(layer),
        })

    # Default GraphEval constraints
    # These can be upgraded later depending on prompt type
    task_def = {
        "id": str(task_id),
        "title": str(graph_data.get("name") or "Generated Graph"),
        "nodes": nodes,
        "constraints": {
            "allowed_layer_diff": [0, 1],
            "max_density": 0.40,
            "feedback_requires_capability": True,
            "feedback_capability_key": "can_feedback",
            "event_capability_key": "can_event",
            "feedback_ratio_max": 0.10,
            "deadly_pairs_block": True,
            "event_to_core_block": False,
            "protected_nodes_key": "is_core",
        },
        "goal": {
            "must_have_edges": [],
            "must_not_have_edges": [],
        },
    }

    return task_def


def graph_to_solution(graph_data: Dict[str, Any], *, solution_id: str = "graph_ai_solution") -> Dict[str, Any]:
    """
    Convert simple graph_data edges into GraphEval solution format.

    Since graph_ai currently uses untyped edges,
    default type is assigned automatically.
    """
    raw_edges = graph_data.get("edges") or []
    typed_edges = []

    for e in raw_edges:
        if not isinstance(e, (list, tuple)) or len(e) < 2:
            continue

        u = str(e[0])
        v = str(e[1])

        # Default edge type:
        # can later become smarter by prompt/domain
        edge_type = "SYNC_CALL"
        typed_edges.append([u, v, edge_type])

    return {
        "id": str(solution_id),
        "edges": typed_edges,
    }


# ---------------------------------------------------------
# Prompt -> pipeline
# ---------------------------------------------------------

def run_prompt_pipeline(
    *,
    prompt: str,
    store_path: str = "memory/memory.jsonl",
    max_steps: int = 6,
    lookback: int = 200,
    task_id: str = "graph_ai_task",
) -> Dict[str, Any]:
    """
    Full Graph AI bridge:

    prompt
    -> generate graph
    -> convert to task
    -> convert to initial solution
    -> run canonical GitCube pipeline
    """
    graph_data = generate_graph_from_prompt(prompt)

    task_def = graph_to_task(graph_data, task_id=task_id)
    initial_solution = graph_to_solution(graph_data, solution_id=task_id)

    out = run_pipeline(
        task_def=task_def,
        initial_solution=initial_solution,
        store_path=store_path,
        max_steps=max_steps,
        lookback=lookback,
    )

    return {
        "prompt": prompt,
        "generated_graph": graph_data,
        "pipeline_result": out,
    }


# ---------------------------------------------------------
# Demo
# ---------------------------------------------------------

def main() -> None:
    import json

    out = run_prompt_pipeline(
        prompt="microservices app",
        store_path="memory/memory.jsonl",
        max_steps=6,
        lookback=200,
        task_id="graph_ai_microservices_demo",
    )

    print(json.dumps(out, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
